config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:index, :show, :edit, :update]
    resources :conversations, only: [:index, :show, :create, :new]
    resources :conversation_replies, only: [:new, :create, :show]
    resource :current_user, only: [:show]
    resources :questions, only: [:show, :index]
    resources :answer_choices, only: [:show]
    resources :user_answers, only: [:show, :new, :create]
  end
  root "static_pages#root"
  get "/auth/:provider/callback", to: "sessions#omniauth"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_demo_user.html.erb
<div id="demo-button-land" class="group">
  <form action="<%= session_url %>" method="post">
    <%= user_auth_token %>
    <input type="hidden" name="user[username]" id="username" value="guest_user">
    <input type="hidden" name="user[password]" id="password" value="password">
    <input type="submit" value="Demo User" class="demo-user-submit">
  </form>
  <p>Don't?</p>
</div>

app/views/static_pages/_dialog_form.html.erb
<div id="dialog-form" title="Sign Up!">
  <%= render partial: "layouts/errors" %>
  <form action="<%= users_url %>" method="post">
    <%= user_auth_token %>
    <label for="username">Username</label>
    <input type="text" name="user[username]" id="username" placeholder="Username" value="<%=params[:username]%>">

    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email" placeholder="Email" value="<%= params[:email]%>">

    <label for="password">Password</label>
    <input type="password" name="user[password]" id="password" placeholder="Password">
  </form>

</div>

app/views/static_pages/_menu.html.erb
<div id="misc-buttons">
  <a class="group" id="codevelop-button" href="">
    <img id="logo-home-link" src="https://s3.amazonaws.com/codevelopavatarproduction/codeveloplogoupdated.png">
  </a>
  <a class="menu-button" href="">Browse Matches</a>
  <a class="menu-button" href="#/profile">Profile</a>
  <a class="menu-button" href="#/messages">Messages</a>
  <div id="sign-out">
    <form action="<%= session_url%>" method="post">
      <%= user_auth_token %>
      <input type="hidden" name="_method" value="DELETE">
      <button class="menu-button">Sign Out</button>
    </form>
  </div>
</div>



<div id="current-user-info">
  <a href="#/profile">
   <img class="face-thumb" src="<%= current_user.avatar.url %>"/>
   <!-- <p><%= current_user.username %></p> -->
  </a>
</div>

app/views/static_pages/root.html.erb
<section class="backdrop">
  <% if not signed_in? %>
  <section class="sign-in">
    <div class="group">
      <a href="session/new" class="btn btn-social btn-codevelop">Sign In</a>
      <p>Have an account?</p>
    </div>
    <%= render partial: 'demo_user' %>
  </section>

  <section class="sign-up-area group">
    <img src="https://s3.amazonaws.com/codevelopavatarproduction/codeveloplogoupdated.png" id="site-title">
    <h2 id="tagline">Find a coding pair whose bugs don't bug you.</h2>
    <div class="language-selection-area">
      <p>I am</p>
      <select class="language-selector group" name="language">
        <option value="none">Language Agnostic</option>
        <option value="ruby">a Rubyist</option>
        <option value="javascript">a Javascripter</option>
        <option value="python">a Pythonista</option>
        <option value="other">a Malbolgean</option>
      </select>
      <button id="continue-button">Continue</button>
    </div>

  </section>
  <section class="footer-links">
    <p><a href="http://appacademy.io">App Academy</a> capstone project by <a href="https://tbescherer.github.io">Thomas Bescherer</a></p>
  </section>
  <% else %>

    <section id="menu-bar" class="group">
    <%= render partial: "menu" %>
    </section>
    <section id="main"></section>
    <script>$(Codevelop.initialize);</script>
  <% end %>
</section>

<%= render partial: "dialog_form" %>